apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ddie5ljgs-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ddie5ljgs-python 
  name: ddie5ljgs-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ddie5ljgs-python 
